baseurl = "http://ikarishinjieva.github.io/tachikoma-blog"
languageCode = "zh-cn"
title = "Tachikoma blog"

[indexes]
	category = "categories"
	tag = "tags"

[permalinks]
	post= "tachikoma-blog/:title/"